apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesight-server
  namespace: kubesight-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubesight-server
  template:
    metadata:
      labels:
        app: kubesight-server
    spec:
      containers:
      - name: kubesight-server
        image: kubesight:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: SERVER_PORT
          value: "8080"
        volumeMounts:
        - name: config
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: kubesight-config
